NEWAPP/Controllers/IITInstituteController.cs
using AutoMapper;
using Data.Repositories.Interfaces;
using DomainModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using NEWAPP.Models;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Text.RegularExpressions;

namespace NEWAPP.Controllers
{
    public class IITInstituteController : Controller
    {
        // GET: IITInstituteController


        public readonly IITInstitute _iTInstitute;
        public readonly IMapper _mapper;
        public IITInstituteController(IITInstitute iTInstitute,IMapper mapper)
        {
            _iTInstitute = iTInstitute;
            _mapper = mapper;   
        }
        public async Task<ActionResult> Index()
        
        {
            List<ITInstitute>  iTInstitutes = await _iTInstitute.GetITInstitutes();
            List<ITInstituteViewModel> iTInstituteViewModels = _mapper.Map<List<ITInstituteViewModel>>(iTInstitutes);
            return View(iTInstituteViewModels);
        }

        // GET: IITInstituteController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: IITInstituteController/Create
        public ActionResult Create()
        {
            ViewBag.CoursesList = new SelectList(new[]
              {
                  new { Id = 1, Name = "C" },
                  new { Id = 2, Name = "C++" },
                  new { Id = 3, Name = ".NET" },
                  new { Id = 4, Name = "Java" },
                  new { Id = 5, Name = "Ruby" },
                  new { Id = 6, Name = "Angular" },
                  new { Id = 7, Name = "React" }
             }, "Id", "Name");
            ITInstituteViewModel iTInstituteViewModel = new ITInstituteViewModel();
            return View(iTInstituteViewModel);
        }

        // POST: IITInstituteController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(ITInstituteViewModel iTInstituteViewModel)
        {
            try
            {
                var instituteViewModel = JsonConvert.SerializeObject(iTInstituteViewModel);
                ITInstituteViewModel instituteViewModel1 = JsonConvert.DeserializeObject<ITInstituteViewModel>(instituteViewModel);
                ITInstitute institute = _mapper.Map<ITInstitute>(instituteViewModel1);
                int id = await _iTInstitute.insert(institute);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: IITInstituteController/Edit/5
        [HttpGet]
        public async Task<ActionResult> Edit(int id)
        {
            ITInstitute institute = await _iTInstitute.GetById(id); // Fetch institute by ID
            if (institute == null)
            {
               return NotFound();
            }
            // Format the ContactNumber to be in the format 111-111-2323
            institute.ContactNumber = Regex.Replace(institute.ContactNumber, @"(\d{3})(\d{3})(\d{4})", "$1-$2-$3");
            ITInstituteViewModel iTInstituteViewModel = _mapper.Map<ITInstituteViewModel>(institute);
            return View("Edit",iTInstituteViewModel);
        }

        // POST: IITInstituteController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(ITInstituteViewModel iTInstituteViewModel)
        {
            try
            {
                var instituteViewModel = JsonConvert.SerializeObject(iTInstituteViewModel);
                ITInstituteViewModel instituteViewModel1 = JsonConvert.DeserializeObject<ITInstituteViewModel>(instituteViewModel);
                ITInstitute institute = _mapper.Map<ITInstitute>(instituteViewModel1);
                int id = await _iTInstitute.update(institute);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: IITInstituteController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: IITInstituteController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

NEWAPP/Views/IITInstitute/Create.cshtml
@model NEWAPP.Models.ITInstituteViewModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>ITInstituteViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        @Html.AntiForgeryToken()
        @using (Html.BeginForm("Create", "IITInstitute", FormMethod.Post))
        {
            <div class="text-danger">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.InstituteID, htmlAttributes: new { @class = "control-label" })
                @Html.TextBoxFor(model => model.InstituteID, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.InstituteID, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.InstituteName, htmlAttributes: new { @class = "control-label" })
                @Html.TextBoxFor(model => model.InstituteName, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.InstituteName, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label" })
                @Html.TextBoxFor(model => model.Location, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.ContactNumber, htmlAttributes: new { @class = "control-label" })
                @Html.TextBoxFor(model => model.ContactNumber, new { @class = "form-control", @id = "ContactNumber" })
                @Html.ValidationMessageFor(model => model.ContactNumber, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.EstablishedYear, htmlAttributes: new { @class = "control-label" })
                @Html.TextBoxFor(model => model.EstablishedYear, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EstablishedYear, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.CoursesOffered, htmlAttributes: new { @class = "control-label" })
                @Html.DropDownListFor(model => model.CoursesOffered, (SelectList)ViewBag.CoursesList,"Select a course", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CoursesOffered, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.FormattedRating, htmlAttributes: new { @class = "control-label" })
                @Html.TextBoxFor(model => model.FormattedRating, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.FormattedRating, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.CreatedDateFormatted, htmlAttributes: new { @class = "control-label" })
                @Html.TextBoxFor(model => model.CreatedDateFormatted, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CreatedDateFormatted, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.ModifiedDateFormatted, htmlAttributes: new { @class = "control-label" })
                @Html.TextBoxFor(model => model.ModifiedDateFormatted, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ModifiedDateFormatted, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        }
    </div>
</div>


<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        $(document).ready(function () {
            // Listen for input changes in the ContactNumber field
            $('#ContactNumber').on('input', function () {
                // Get the input value and remove any non-numeric characters
                var value = $(this).val().replace(/\D/g, '');

                // Format the phone number with dashes (XXX-XXX-XXXX)
                if (value.length <= 3) {
                    $(this).val(value);
                } else if (value.length <= 6) {
                    $(this).val(value.substring(0, 3) + '-' + value.substring(3));
                } else {
                    $(this).val(value.substring(0, 3) + '-' + value.substring(3, 6) + '-' + value.substring(6, 10));
                }
            });
        });
    </script>
}

NEWAPP/Views/IITInstitute/Edit.cshtml
@model NEWAPP.Models.ITInstituteViewModel

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>ITInstituteViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        @Html.AntiForgeryToken()
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="InstituteID" class="control-label"></label>
                <input asp-for="InstituteID" class="form-control" />
                <span asp-validation-for="InstituteID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="InstituteName" class="control-label"></label>
                <input asp-for="InstituteName" class="form-control" />
                <span asp-validation-for="InstituteName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Location" class="control-label"></label>
                <input asp-for="Location" class="form-control" />
                <span asp-validation-for="Location" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ContactNumber" class="control-label"></label>
                <input asp-for="ContactNumber" class="form-control" id="contactNumber" />
                <span asp-validation-for="ContactNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EstablishedYear" class="control-label"></label>
                <input asp-for="EstablishedYear" class="form-control" />
                <span asp-validation-for="EstablishedYear" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CoursesOffered" class="control-label"></label>
                <input asp-for="CoursesOffered" class="form-control" />
                <span asp-validation-for="CoursesOffered" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FormattedRating" class="control-label"></label>
                <input asp-for="FormattedRating" class="form-control" />
                <span asp-validation-for="FormattedRating" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreatedDateFormatted" class="control-label"></label>
                <input asp-for="CreatedDateFormatted" class="form-control" type="datetime-local" />
                <span asp-validation-for="CreatedDateFormatted" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ModifiedDateFormatted" class="control-label"></label>
                <input asp-for="ModifiedDateFormatted" class="form-control" type="datetime-local" />
                <span asp-validation-for="ModifiedDateFormatted" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/inputmask/5.0.8-beta.5/jquery.inputmask.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#contactNumber').inputmask('999-999-9999'); // Define the phone number format
        });
    </script>
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

NEWAPP/Views/IITInstitute/Index.cshtml
@model List<ITInstituteViewModel>;

@{
    ViewData["Title"] = "IT Institutes";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>IT Institutes</h2>
<div class="mb-3">
    <a asp-controller="IITInstitute" asp-action="Create" class="btn btn-primary">
        Create New Institute
    </a>
</div>
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Institute ID</th>
            <th>Institute Name</th>
            <th>Location</th>
            <th>Contact Number</th>
            <th>Established Year</th>
            <th>Courses Offered</th>
            <th>Rating</th>
            <th>Created Date</th>
            <th>Modified Date</th>
        </tr>
    </thead>
    <tbody>
        @if (Model != null && Model.Any())
        {
            foreach (ITInstituteViewModel institute in Model)
            {
                <tr>
                    <td>@institute.InstituteID</td>
                    <td>
                        <a asp-controller="IITInstitute"
                           asp-action="Edit"
                           asp-route-id="@institute.InstituteID">
                            @institute.InstituteName
                        </a>
                    </td>

                    <td>@institute.Location</td>
                    <td>@institute.ContactNumber</td>
                    <td>@(institute.EstablishedYear.HasValue ? institute.EstablishedYear.ToString() : "N/A")</td>
                    <td>@institute.CoursesOffered</td>
                    <td>@institute.FormattedRating</td>
                    <td>@institute.CreatedDateFormatted</td>
                    <td>@institute.ModifiedDateFormatted</td>

                </tr>
            }
        }
        else
        {
            <tr>
                <td colspan="9" class="text-center">No records found</td>
            </tr>
        }
    </tbody>
</table>



<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    function editInstitute(instituteId) {
        $.ajax({
            url: '/IITInstitute/Edit/' + instituteId,
            type: 'GET',
            success: function (data) {debugger
            },
            error: function (xhr, status, error) {
                console.error('Error fetching data: ' + error);
                alert('An error occurred while trying to fetch the details.');
            }
        });
    }
</script>