NEWAPP/Models/FlatViewModel.cs
using DomainModels;

namespace NEWAPP.Models
{
    public class FlatViewModel
    {
        public int FlatID { get; set; }
        public int PropertyOwnerID { get; set; }
        public string FlatNumber { get; set; }
        public string Address { get; set; }
        public string Gender { get; set; } // Male, Female, Other, etc.


        public bool IsActive { get; set; } = true;
        public PropertyOwnerViewModel PropertyOwner { get; set; }
        public List<PropertyOwnerViewModel> PropertyOwners { get; set; } 
    }
}

NEWAPP/Controllers/FlatController.cs
using AutoMapper;
using Data.Repositories.Interfaces;
using DomainModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using NEWAPP.Models;
using System.Collections.Generic;

namespace NEWAPP.Controllers
{
    public class FlatController : Controller
    {
        private readonly IFlat _flat;
        private readonly IMapper _mapper;
        private readonly IPropertyOwners _propertyOwners;
        public FlatController(IFlat flat,IMapper mapper,IPropertyOwners propertyOwners) { 
            _flat = flat;
            _mapper = mapper;
            _propertyOwners = propertyOwners;
        
        }
        // GET: FlatController
        public async Task<ActionResult> Index()
        {
            List<Flat> flats = await _flat.GetFlatsAsync();
            List<FlatViewModel> flatViewModel = _mapper.Map<List<FlatViewModel>>(flats);
            return View(flatViewModel);
        }

        // GET: FlatController/Details/5
        public  ActionResult Details(int id)
        {
           // await _flat.Delete(id);
            return View();
        }

        // GET: FlatController/Create
        // GET: FlatController/Create
        public async Task<ActionResult> Create()
        {
            FlatViewModel viewModel = new FlatViewModel();

            // Fetch PropertyOwners list
            List<PropertyOwners> propertyOwners = await _propertyOwners.GetPropertyOwners();

            // Map to the correct ViewModel type
            List<PropertyOwnerViewModel> propertyOwnerViewModels = _mapper.Map<List<PropertyOwnerViewModel>>(propertyOwners);

            // Assign correctly
            viewModel.PropertyOwners = propertyOwnerViewModels;

            return View(viewModel);
        }


        // POST: FlatController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(FlatViewModel viewModel)
        {
            try
            {
                Flat flat = _mapper.Map<Flat>(viewModel);
                await _flat.Insert(flat);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: FlatController/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            Flat flat = await _flat.GetFlatByIdAsync(id);
            FlatViewModel flatViewModel = _mapper.Map<FlatViewModel>(flat);
            // Fetch PropertyOwners list
            List<PropertyOwners> propertyOwners = await _propertyOwners.GetPropertyOwners();

            // Map to the correct ViewModel type
            List<PropertyOwnerViewModel> propertyOwnerViewModels = _mapper.Map<List<PropertyOwnerViewModel>>(propertyOwners);

            // Assign correctly
            flatViewModel.PropertyOwners = propertyOwnerViewModels;
            return View(flatViewModel);
          //  return View();
        }

        // POST: FlatController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, FlatViewModel viewModel)
        {
            try
            {
                Flat flat = _mapper.Map<Flat>(viewModel);
                await _flat.Update(flat);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: FlatController/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            Flat flat =  await _flat.GetFlatByIdAsync(id);
            FlatViewModel flatViewModel = _mapper.Map<FlatViewModel>(flat); 
            return View(flatViewModel);
        }

        // POST: FlatController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(int id, IFormCollection collection)
        {
            try
            {
                await _flat.Delete(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

NEWAPP/Views/Flat/Create.cshtml
@model FlatViewModel
@using DomainModels;
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>FlatViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        @using (Html.BeginForm("Create", "Flat", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                @Html.LabelFor(model => model.FlatID, new { @class = "control-label" })
                @Html.TextBoxFor(model => model.FlatID, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.FlatID, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.PropertyOwnerID, new { @class = "control-label" })
                @Html.DropDownListFor(model => model.PropertyOwnerID, new SelectList(Model.PropertyOwners, "PropertyOwnerID", "OwnerFullName"),"--Please Select--" ,new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PropertyOwnerID, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.FlatNumber, new { @class = "control-label" })
                @Html.TextBoxFor(model => model.FlatNumber, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.FlatNumber, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Address, new { @class = "control-label" })
                @Html.TextBoxFor(model => model.Address, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                <label class="control-label">Gender</label><br />
                @foreach (var gender in Enum.GetValues(typeof(Gender)))
                {
                    <label class="radio-inline">
                        @Html.RadioButtonFor(model => model.Gender, gender) @gender
                    </label>
                }
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>

            <!-- IsActive Checkbox -->
            <div class="form-group">
                <label class="control-label">
                    @Html.CheckBoxFor(model => model.IsActive) Is Active
                </label>
                @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        }
    </div>
</div>

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

NEWAPP/Views/Flat/Delete.cshtml
@model NEWAPP.Models.FlatViewModel

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>FlatViewModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FlatID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FlatID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PropertyOwnerID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PropertyOwnerID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FlatNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FlatNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

NEWAPP/Views/Flat/Edit.cshtml
@model NEWAPP.Models.FlatViewModel
@using DomainModels;
@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>FlatViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        @using (Html.BeginForm("Edit", "Flat", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                @Html.LabelFor(model => model.FlatID, new { @class = "control-label" })
                @Html.TextBoxFor(model => model.FlatID, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.FlatID, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.PropertyOwnerID, new { @class = "control-label" })
                @Html.DropDownListFor(model => model.PropertyOwnerID, new SelectList(Model.PropertyOwners, "PropertyOwnerID", "OwnerFullName"),"--Please Select--", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PropertyOwnerID, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.FlatNumber, new { @class = "control-label" })
                @Html.TextBoxFor(model => model.FlatNumber, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.FlatNumber, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Address, new { @class = "control-label" })
                @Html.TextBoxFor(model => model.Address, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                <label class="control-label">Gender</label><br />
                @foreach (var gender in Enum.GetValues(typeof(Gender)))
                {
                    <label class="radio-inline">
                        @Html.RadioButtonFor(model => model.Gender, gender) @gender
                    </label>
                }
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>

            <!-- IsActive Checkbox -->
            <div class="form-group">
                <label class="control-label">
                    @Html.CheckBoxFor(model => model.IsActive) Is Active
                </label>
                @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        }
    </div>
</div>

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Html.Partial("_ValidationScriptsPartial")
}

NEWAPP/Views/Flat/Index.cshtml
@model IEnumerable<NEWAPP.Models.FlatViewModel>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FlatID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PropertyOwnerID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PropertyOwner.OwnerFullName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FlatNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Gender)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsActive)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.FlatID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PropertyOwnerID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PropertyOwner.OwnerFullName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FlatNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Address)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Gender)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IsActive)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.FlatID }) |

                    @Html.ActionLink("Delete", "Delete", new { id = item.FlatID })
                </td>
            </tr>
        }
    </tbody>
</table>